ERROR: Unable to locate a modulefile for 'python/3.9'
Unable to init server: Could not connect: Connection refused
Unable to init server: Could not connect: Connection refused

(plot.py:456913): Gdk-CRITICAL **: 23:04:42.019: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
slurmstepd-slurm1: error: *** JOB 328512 ON slurm1 CANCELLED AT 2024-11-09T23:04:46 ***
